### ISSUE TITLE
[BUG] json_decode: expected key string at

### ISSUE THREAD

**Issue by Fortage** [PhlexPlexico/get5-web#104]
Which Build
master

The match does not start with get5-web. writes error 

{"available": 1, "gamestate": 0, "avaliable": 1, "plugin_version": "0.7.1"}
L 06/29/2019 - 09:43:19: [get5.smx] json_decode: expected key string at 404
L 06/29/2019 - 09:43:19: [get5.smx] Failed to load match config: invalid match json

Before that, there was a get5-web from splewis and everything worked. Put your web assembly and start producing such an error.

**Comment by PhlexPlexico** [comment]
And which site are you using? Mine or splewis'? Could you please post the match config, this can be found by going to `https://yourget5instance.com/match/<MATCHNUMBER>/config` and paste the JSON here. It shouldn't be malformed. 

This web-panel is using the latest builds from get5 itself. It's possible that it may not work with older versions.

**Comment by Fortage** [comment]
I used your site. 
here is json

{
  "cvars": {
    "get5_web_api_url": "http://get5.uralgamearea.ru/"
  }, 
  "maplist": [
    "de_dust2", 
    "de_inferno", 
    "de_mirage", 
    "de_nuke", 
    "de_overpass", 
    "de_train", 
    "de_vertigo"
  ], 
  "maps_to_win": 1, 
  "match_title": "", 
  "matchid": "7", 
  "side_type": "standard", 
  "skip_veto": false, 
  "team1": {
    "flag": "RU", 
    "name": "3D", 
    "players": {}, 
    "tag": "3D"
  }, 
  "team2": {
    "flag": "RU", 
    "name": "Team1", 
    "players": {}, 
    "tag": "Team1"
  }, 
  "veto_first": "team1"
}


I have the latest version of the splewis site and it works. When I use your version, it gives this error.

**Comment by PhlexPlexico** [comment]
And what version of the API_stats are you using?

**Comment by Fortage** [comment]
I tried different versions. At first I tried to compile using spcomp. Then it downloaded which was in / releases. Then I tried to download get5_apistats.sp from splewis and copy it from myself. Nothing helped.

**Comment by PhlexPlexico** [comment]
I mean specifically the get5 plugin. Try using the last successful build on the repository, and reloading the plugin. There is no reason it shouldn't be working, as I have 3 instances running with no issues either, and I can't reproduce it on my end.

**Comment by Fortage** [comment]
I am using the latest version of get5 dated February 17, version 0.7.1. Because I installed it only in March of this year.

**Comment by PhlexPlexico** [comment]
If you click the ["Build Passing"](https://ci.splewis.net/job/get5/) icon on the repository, you can access a build that was last made in June. It's 0.7.2-DEV, but please give that a try.

**Comment by Fortage** [comment]
Oh, thank you very much. I will keep in mind in the future that you need to compare assemblies not with github but with this site. Thanks again!
