### ISSUE TITLE
Link To Installation Notes

### ISSUE THREAD

**Issue by dMwJr** [PhlexPlexico/get5-web#105]
Just wanted to let you know that the instructions link on the main git-hub page is broke, you can still get to it but new people might get lost. Just FYI

**Comment by PhlexPlexico** [comment]
It's already been noted. And in the development branch. Just have yet to push it to master is all, thanks for the heads up! Going to pin this and leave this here: 

https://github.com/PhlexPlexico/get5-web/wiki/Installation
