### ISSUE TITLE
[BUG] Player Leaderboard alignment

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#114]
**Describe the bug**
Alignment is not proper for Player Leaderboard

**Which Build**
development

**To Reproduce**
1. Go to Web Panel
2. Click on Leaderboards
3. Select Individual Leaderboard
4. See alignment

**Expected behavior**
Proper alignment

**Additional context**

**Comment by xe1os** [comment]
@PhlexPlexico, @TandelK has already helped you with previous web page alignments. He might do this as well.

**Comment by TandelK** [comment]
Will look into it once gets free from other work. @xe1os can you drop me Screenshot if possible.

**Comment by xe1os** [comment]
@TandelK [http://prnt.sc/oqvb2n](url)

**Comment by PhlexPlexico** [comment]
Thanks for throwing this out there :) should be fixed, just click the headers to sort, there's no more buttons (which looked gaudy to me, anyways).

**Comment by xe1os** [comment]
@PhlexPlexico Thank you for the help.

It fixed for me when i removed below from statleaderboard.html
`<div class="panel panel-default">`

**Comment by xe1os** [comment]
> Thanks for throwing this out there :) should be fixed, just click the headers to sort, there's no more buttons (which looked gaudy to me, anyways).

Thank you so much :) <3 @PhlexPlexico
