### ISSUE TITLE
[Feature Request] Season wise Player Leaderboard

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#115]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Player leaderboard for specific season / season wise

**Describe alternatives you've considered**
No

**Additional context**
It will be really helpful to find the top players for a specific season.

**Comment by xe1os** [comment]
@PhlexPlexico i still can't find this working.
Player stats for a particular season is what i meant.

**Comment by PhlexPlexico** [comment]
You got it. If you navigate off to `leaderboard/season/<season ID>/players`, it will show all player stats for everyone in that season!

**Comment by xe1os** [comment]
@PhlexPlexico there seems to be a bug with the Season wise Player stats.
I have checked couple of seasons. Players stats are exactly the same when compared between the seasons. All the seasons are showing the same stats for all players.

Below are the screenshots taken.
http://prnt.sc/ov8b6u
http://prnt.sc/ov8bg9

**Comment by PhlexPlexico** [comment]
Yeah I think I know where the problem is, it's just the logic in the way players are collected. I'll look into this later here and push out a patch.
