### ISSUE TITLE
[BUG] Error reading get5_web_avaliable response from plugin

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-web#118]
After compiling the plugin and using with the panel i came across this issue 
`Error reading get5_web_avaliable response` 

This issue will be always there as System2 and SteamWorks handles request seperately as per old splewis info

https://github.com/splewis/get5/issues/86

**Comment by TandelK** [comment]
https://github.com/dordnung/System2/releases

**Comment by PhlexPlexico** [comment]
Are you using the compiled smx within the release page?

**Comment by PhlexPlexico** [comment]
Also, if you're using the web panel with the temp server, it's not going to work as you're trying to create a match with the URL `localhost` which will fail.

**Comment by PhlexPlexico** [comment]
Going from the SMX used in the [releases](https://github.com/phlexplexico/get5-web/releases/tag/0.3) page, I am able to fully start a match, and get the response from the webserver just fine. I cannot reproduce.

What version of get5 are you using? I'm using the latest development build.

**Comment by TandelK** [comment]
I tried deploying yesterday Master branch.

**Comment by PhlexPlexico** [comment]
I cannot recreate, and the only time system2 is used is during the FTP call (and optional compress). Otherwise, Steam works is handling the HTTP requests. Does release 0.2 work?

**Comment by PhlexPlexico** [comment]
Also I'm inclined to believe this is more of a get5 problem, since get5_loadmatch_from_url exists in get5, and not this plugins territory.

**Comment by PhlexPlexico** [comment]
I'm going to assume there is no more issue with this?
