### ISSUE TITLE
[Feature Request] Match Date and Season Name on /matches page

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#129]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Would like to see the match date and the season name in /matches page for ongoing matches as well as completed matches.

**Describe alternatives you've considered**
None.

**Additional context**
Aligning the columns and utilising the additional space after MatchID, Status and Owner

**Comment by PhlexPlexico** [comment]
Resolved in development. Take a look and tell me if it's what you need!

**Comment by xe1os** [comment]
@PhlexPlexico Yes! this is what i was looking for. Thank you so much :)

**Comment by xe1os** [comment]
@PhlexPlexico need some minor formatting for pending matches.

Start Time and End Time can be `-` for the matches that are pending.

Please find the screenshot for better understanding
https://prnt.sc/p6o0ix

**Comment by PhlexPlexico** [comment]
I believe that should be updated now, I made that change on Friday
