### ISSUE TITLE
[Feature Request] Total Number of matches completed in a Season

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#132]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Would like to know the total number of matches played so far in a season on /seasons page

**Describe alternatives you've considered**
None.

**Additional context**
Would help us to know how many matches are completed in a season instead of counting from /matches page.

**Comment by PhlexPlexico** [comment]
I think as a workaround for now, you can use the Team Leaderboard in seasons, which shows the total maps won/lost per each team.

**Comment by PhlexPlexico** [comment]
Resolved in last push to [development branch](https://github.com/PhlexPlexico/get5-web/commit/e671e65e6cdf07158a2eaa2bd42f8d558daac300).
