### ISSUE TITLE
[Feature Request] Optional Player Name to be part of config file

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#137]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Option to enable/disable Optional Match Name from /team/create

**Describe alternatives you've considered**
To have an option in prod_config where we can enable/disable Optional Match Name.

Like we have CREATE_MATCH_TITLE_TEXT to enable/disable.

**Additional context**
Nothing.

**Comment by PhlexPlexico** [comment]
Feature is in dev and headed toward master branch now.
