### ISSUE TITLE
[BUG] Demos are not getting uploaded on FTP (vsftpd)

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#141]
**Describe the bug**
After match completion demos are getting zipped but not getting uploaded to ftp.

**Which Build**
master

**To Reproduce**
1. Complete the match
2. Go to web panel and click on Match ID that you want to download the demo
3. Click on Download Demo
4. See error - "The requested URL was not found on this server."

**Expected behavior**
I'm able to upload the .zip files manually on FTP with the same credentials mentioned  in get5api.cfg

**Additional context**
Below is the content of get5api.cfg

// 0 Disables FTP Upload, 1 Enables.
// -
// Default: "0"
get5_api_ftp_enabled "1"

// Remote FTP Host. Make sure you do NOT have the trailing slash. Include the path to the directory you wish to have.
// -
// Default: "ftp://example.com"
get5_api_ftp_host "ftp://web.xe1os.com"

// Password for the FTP user. Leave blank if no password.
// -
// Default: "supersecret"
get5_api_ftp_password "XXXXXXX"

// Remote FTP Port
// -
// Default: "21"
get5_api_ftp_port "21"

// Username for the FTP connection.
// -
// Default: "username"
get5_api_ftp_username "XXXXX"

// 0 Disables zipping files, 1 enables.
// -
// Default: "0"
get5_enabled_7z_compression "1"

**Comment by PhlexPlexico** [comment]
Try without compression and tell me the results?

**Comment by xe1os** [comment]
> Try without compression and tell me the results?


Tried makeng get5_enabled_7z_compression "0" still doesn't work. Able to open ftp directory with Windows explorer, Filezilla and WinSCP still auto upload ain't working.

**Comment by xe1os** [comment]
I might be missing some FTP configuration.

**Comment by PhlexPlexico** [comment]
Hmm I believe I'm using vsftpd on a raspberry pi and it's working. Is there any log of the user trying to log in any ftp logs? Is there any error being thrown by the plugin?

**Comment by xe1os** [comment]
> Hmm I believe I'm using vsftpd on a raspberry pi and it's working. Is there any log of the user trying to log in any ftp logs? Is there any error being thrown by the plugin?

Hi @PhlexPlexico , can you share the vsftpd.conf that you are using?

**Comment by xe1os** [comment]
`'Create FTP')
			# Creating FTP User
		if [ $(id -u) -eq 0 ]; then
			read -p "Enter FTP username : " username
			read -s -p "Enter password : " password
			egrep "^$username" /etc/passwd >/dev/null
		if [ $? -eq 0 ]; then
			echo "$username exists!"
			exit 1
			else
			pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
			echo $pass
			useradd -m -p $pass -s /bin/bash $username
			[ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
		fi
				
			else
			echo "Only root may add a user to the system"
			exit 2
		fi
			# Download and install vsftpd
		if [ -f "/etc/vsftpd.conf" ]
			then
			echo "vsftpd instance already exist"
			else	
			echo "vsftpd install..."
			apt -y install vsftpd
			echo "What is your instance Public IP ?"
			read ip
			echo "Enter FTP PASV min port (eg. 12000)"
			read pasvminport
			echo "Enter FTP PASV max port (eg. 12100)"
			read pasvmaxport
			
			echo "Port Range entered for FTP Passive is $pasvminport-$pasvmaxport

			# Modifying vsftdp.conf
			echo "Backing up default vsftpd.conf file"
			mv /etc/vsftpd.conf /etc/vsftpd.conf.bak

			vsftpd="/etc/vsftpd.conf"

			echo "allow_writeable_chroot=YES" >> $vsftpd
			echo "anon_umask=022" >> $vsftpd
			echo "anon_upload_enable=NO" >> $vsftpd
			echo "anonymous_enable=NO" >> $vsftpd
			echo "ascii_download_enable=YES" >> $vsftpd
			echo "ascii_upload_enable=YES" >> $vsftpd
			echo "chmod_enable=YES" >> $vsftpd
			echo "chroot_local_user=YES" >> $vsftpd
			echo "connect_from_port_20=YES" >> $vsftpd
			echo "dirmessage_enable=YES" >> $vsftpd
			echo "dual_log_enable=YES" >> $vsftpd
			echo "file_open_mode=0755" >> $vsftpd
			echo "force_dot_files=YES" >> $vsftpd
			echo "listen=YES" >> $vsftpd
			echo "local_enable=YES" >> $vsftpd
			echo "local_root=/var/www/get5-web/get5/static" >> $vsftpd
			echo "local_umask=002" >> $vsftpd
			echo "max_clients=100" >> $vsftpd
			echo "max_per_ip=10" >> $vsftpd
			echo "pam_service_name=vsftpd" >> $vsftpd
			echo "pasv_enable=YES" >> $vsftpd
			echo "pasv_address=$ip" >> $vsftpd
			echo "pasv_min_port=$pasvminport" >> $vsftpd
			echo "pasv_max_port=$pasvmaxport" >> $vsftpd
			echo "seccomp_sandbox=NO" >> $vsftpd
			echo "tcp_wrappers=YES" >> $vsftpd
			echo "use_localtime=YES" >> $vsftpd
			echo "userlist_deny=NO" >> $vsftpd
			echo "userlist_enable=YES" >> $vsftpd
			echo "userlist_file=/etc/vsftpd.userlist" >> $vsftpd
			echo "write_enable=YES" >> $vsftpd
			echo "xferlog_enable=YES" >> $vsftpd
			echo "xferlog_std_format=YES" >> $vsftpd
	
			# Setting Permissions
			echo "$username" >> /etc/vsftpd.userlist
			echo "Setting folder permissions for $username"
			sudo usermod -a -G www-data $username
			sudo usermod -d /var/www/get5-web/get5/static/ $username
			sudo chown -R $username:www-data /var/www/get5-web/get5/static
			sudo chmod 0775 -R /var/www/get5-web/get5/static/

			echo "Restarting vsftpd service"
			service vsftpd restart

			echo "Please forward the ports range 20-21(tcp) & $pasvminport-$pasvmaxport(tcp)"
			echo "Done."
		fi
	;;
        'Remove Get5-Web')
                echo "Do you wish to remove get5-web?"
                        read -p "True or False: " remove
                        while [[ $remove != @("True"|"False") ]]
                                do
                                echo "Please enter only True or False"
                                read -p "True or False :" remove
                        done
                        if [ $remove == "True" ]
                        then
                echo "Removing get5-web folder"
                rm -r /var/www/get5-web
                echo "Please enter the site name to uninstall without www"
                read sitename
                rm -r /etc/apache2/sites-enabled/$sitename.conf

                read -p "YOUR SQL ROOT PASSWORD: " -s rootpasswd
                until mysql -u root -p $rootpasswd  -e ";" ; do
                read -p "Can't connect, please retry Root Password: " -s rootpasswd
                done
                echo "Taking mysql backup"
                mysql -u root -p $rootpasswd get5 > get5-$(date +%F).sql
                echo "Deleting database"
                mysql -u root -p $rootpasswd -e "DROP USER 'get5'@'localhost';"
                mysql -u root -p $rootpasswd -e "DROP DATABASE get5;"
                mysql -u root -p $rootpasswd -e "FLUSH PRIVILEGES;"
                fi`

**Comment by xe1os** [comment]
@PhlexPlexico thanks for the help.

Demos are getting uploaded if the compression is disabled in getapi.cfg

Thanks again :)
