### ISSUE TITLE
[Enhancement] Remove Compression From Plugin

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/get5-web#142]
**Is your feature request related to a problem? Please describe.**
Compression either doesn't work, or works half the time. This is probably due to a timing thing and then the demo is usually deleted before the zip file can be uploaded to the ftp server.

**Describe the solution you'd like**
Just remove compression as it doesn't work.

**Describe alternatives you've considered**
Fixing wouldn't be worth the time, so it's best just to remove it.

**Additional context**
N/A

**Comment by xe1os** [comment]
@PhlexPlexico demos are not getting deleted after compression. We can see both .dem and .zip files in the csgo folder. i think its failing to upload .zip after compression.

**Comment by PhlexPlexico** [comment]
I'm pretty sure it's a race condition within system2. I've had it delete demos before much to the dismay of players. So I'd rather not have it happen to anyone else :)

**Comment by TandelK** [comment]
@PhlexPlexico can we link FTP to other location and use that link with config file to locate Demos ?  Like i can use my Unlimited Web Host Service for Demo Uploads and use that link with config file for adding demos to the panel where Data Transfer is limited .

**Comment by xe1os** [comment]
> @PhlexPlexico can we link FTP to other location and use that link with config file to locate Demos ? Like i can use my Unlimited Web Host Service for Demo Uploads and use that link with config file for adding demos to the panel where Data Transfer is limited .

@PhlexPlexico this would help alot.

**Comment by PhlexPlexico** [comment]
Please create a seperate ticket if you wish to request that so others may be able to see it.

**Comment by TandelK** [comment]
@PhlexPlexico Currently we know that Compression of Demos is not possible via System2 version, but i just came across plugin and extension that does support lot of protocols you might already know 
`cURL & Hash - https://forums.alliedmods.net/showthread.php?t=152216`

Also the way someone has already created Auto Demo Upload function 
tEasyFTP - `https://forums.alliedmods.net/showthread.php?p=1629724`
tAutoDemoUpload - https://forums.alliedmods.net/showthread.php?p=1517461`

Which are currently working perfectly. Is there any way we can change from System2 to this method 
?

**Comment by PhlexPlexico** [comment]
PRs are welcome if someone wishes to change the functionality of uploads. I don't have the capacity to work on this project anytime soon, and I know compression is very possible with System2, it's just how it's implemented in the plugin.
