### ISSUE TITLE
[Feature Request] Sub-Season Functionality

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#146]
**Is your feature request related to a problem? Please describe.**
It would be great if we have sub-season functionality in order to organise larger tournaments.
Eg. Tournament that runs for more than 6months.

**Describe the solution you'd like**
Example :
Season Name - ESL Pro League Season 10
Sub-Seasons - ESL Pro League S10 - America, ESL Pro League S10 -  Asia, etc...

Option to have sub-season available while creating match. And it would be even better if we assign or lock admins to the season/sub-season on web panel.

**Describe alternatives you've considered**
No.

**Additional context**
Both Season and Sub-Season wise players and team stats.

**Comment by PhlexPlexico** [comment]
I personally won't be working on this, as I do not see much of a point. Even with larger tournaments, different divisions would use different leaderboards which are effectively different seasons.
