### ISSUE TITLE
[BUG] Not able to access match as SA or Admin

### ISSUE THREAD

**Issue by bjerrecs** [PhlexPlexico/get5-web#147]
**Describe the bug**
Installed the Get5 Web as per standard.
Can create matches, seasons and more.

All works fine.

But i cant access the match while its live?

Here are the screenshots off the results of pressing the match ID buttom.

First screenshot of error is from superadmin and the other is from a normal admin
![chrome_Zg69EGQ6PP](https://user-images.githubusercontent.com/32055984/67150242-65a7aa00-f2b5-11e9-9d19-fd1586c8c035.png)
![chrome_8HKpO1uX40](https://user-images.githubusercontent.com/32055984/67150243-66404080-f2b5-11e9-80d9-45778d869081.png)
![chrome_p1hd2ZTaNo](https://user-images.githubusercontent.com/32055984/67150244-66404080-f2b5-11e9-96bd-4e573217ec95.png)

**Which Build**
Get5 d0477c6+

**Comment by PhlexPlexico** [comment]
Please attach the appropriate log file so I can further investigate, thanks! It'll be in the logs directory.

**Comment by PhlexPlexico** [comment]
Wait, actually found it. https://github.com/PhlexPlexico/get5-web/blob/master/get5/match.py#L699 just needs to be `list_admin` not `lis_admin`. Will fix.

**Comment by PhlexPlexico** [comment]
PR #148  should fix this. Please confirm, thanks!

**Comment by MikkelDK** [comment]
I can confirm, this happens if I **setting 1 match** to being: **Private Match**

`Sorry, unexpected error: 'BaseQuery' object is not callable` - and this happens, if I edit on database set **match 1 to being private match** and **clicking on the match (as admin, and I get the error!)**

**Comment by PhlexPlexico** [comment]
And are you running the latest version after PR #148 was updated? If so, please supply the log at the time of error. Thanks!

**Comment by MikkelDK** [comment]
> And are you running the latest version after PR #148 was updated? If so, please supply the log at the time of error. Thanks!

Yes, I did installed it yesterday! ;) if I looking on Match.py (it's updated, as you did fixed! with "lis_admin" to "is_admin" ;)

Pastebin for errors: https://pastebin.com/wMDyjsLp

**Comment by PhlexPlexico** [comment]
[For reference](https://github.com/PhlexPlexico/get5-web/blob/master/get5/match.py#L701) this is where it's failing and it's to do with logic of selecting the `PlayerStats` model. Will look into later.

**Comment by PhlexPlexico** [comment]
Latest development push should fix it.

**Comment by bjerrecs** [comment]
Can confirm the fix worked on my end! Thanks!
