### ISSUE TITLE
[BUG] No Access to Logo Upload. (Create Team)

### ISSUE THREAD

**Issue by MikkelDK** [PhlexPlexico/get5-web#149]
**Describe the bug**
No access to/can't see "**Upload Logo**" under create a team as "**is_admin OR super_admin**"

**Which Build**
happening on the master build.

**To Reproduce**
1. Go to 'http://get5.lindhost.eu/'
2. Click on 'Sign on Steam'
3. Go to Teams > Create a Team

**Expected behavior**
I can't see "**Upload Logo**", seems it's invisible (no AdBlock) tested on edge on a second account.

**Additional context**
![get5web](https://i.gyazo.com/bb1717396be25afb1fcad0b50b30aa8b.png)

**Comment by PhlexPlexico** [comment]
Are you listed both as an admin and super admin in your config?

**Comment by MikkelDK** [comment]
> Are you listed both as an admin and super admin in your config?

@PhlexPlexico Yep. both and tested with "Admin" and with "super admin"

Still no "Logo Upload" :'(

**Comment by PhlexPlexico** [comment]
Try with just one, and paste your portion of the config here. It's still working on my instance and I can see it just fine.

**Comment by MikkelDK** [comment]
Nope. ;( nothing here.

**Comment by PhlexPlexico** [comment]
What do you mean nothing? I need to see the values of your Config, specifically these values only: 
SUPER_ADMIN_IDS = []
ADMIN_IDS = []

**Comment by MikkelDK** [comment]
```
ADMIN_IDS = [76561198383180718]
SUPER_ADMIN_IDS = []
```
I did too tried with this:
```
ADMIN_IDS = []
SUPER_ADMIN_IDS = [76561198383180718]
```

**Comment by PhlexPlexico** [comment]
Don't use integers, they're strings. Try surrounding in quotes.

`SUPER_ADMIN_IDS = ["76561198383180718"]`

**Comment by MikkelDK** [comment]
> Don't use integers, they're strings. Try surrounding in quotes.
> 
> `SUPER_ADMIN_IDS = ["76561198383180718"]`

Cool, it works. just weird. why "" is removed on prod config ;/

**Comment by PhlexPlexico** [comment]
Because prod config is meant to be empty. The application can run without any admins or intervention from that file.

**Comment by MikkelDK** [comment]
I see. ;) //fixed.
