### ISSUE TITLE
[Feature Request] Change servername after match finish?

### ISSUE THREAD

**Issue by MikkelDK** [PhlexPlexico/get5-web#153]
**Describe the bug**
(apistats or get5 plugin?) or somehow changes servername back (from server.cfg) after the match finishes (e.g: 16-0) - with get5

**Which Build**
master.

**To Reproduce**
1. Create a match
2. Play the match.
3. Finish match after 16-0.
4. Servername is still: Get5: Team1 vs Team2

**Expected behavior**
It should change the servername from the "server.cfg" where hostname is inserted. 
Example: MrC4t Server.

**Comment by PhlexPlexico** [comment]
That's more of a get5 question I would think, as I feel like that should be a feature of get5 when a match ends.

**Comment by PhlexPlexico** [comment]
For right now, I'm going to label this as wontfix and help wanted, as it would be something easy as a first issue if someone wants to modify the sourcemod plugin.

**Comment by TandelK** [comment]
This will require a bit of rework after Get5 finish all the events not after Map Change because if there are BO2 or more it wont work. Just need to add command to execute server.cfg where hostname might be set to exec after match/series completion.

**Comment by PhlexPlexico** [comment]
Uhhh not really, it won't. What I would recommend is creating a new value for the API Stats plugin. Name it something such as `g_DefaultServerNameCvar` and create a convar that can be stored in the config file. Once that's done you use some sourcemod magic to get and set the convarstring `hostname` on the series result in the plugin, for example [here](https://github.com/PhlexPlexico/get5-web/blob/development/sourcemod_plugin/get5_apistats/scripting/get5_apistats.sp#L572).

**Comment by PhlexPlexico** [comment]
I saw that you created a ticket with the get5 plugin, and it seems that is supposed to be the intended functionality of get5. Would you mind if we closed this ticket, since it's more relational to that plugin?
