### ISSUE TITLE
[BUG] apistats plugin.

### ISSUE THREAD

**Issue by MikkelDK** [PhlexPlexico/get5-web#162]
**Describe the bug**
Plugin get5_apistats.smx failed to load: Unable to load plugin (no debug string table).

**Which Build**
master

**Expected behavior**
It will not load.

**Additional context**
`[SM] Failed to load plugin "get5_apistats.smx": Unable to load plugin (no debug string table).`

**Comment by PhlexPlexico** [comment]
This is most likely because I've had to setup a new environment for sourcemod for myself. Tried using WSL with some 32bit fixes. I'll recompile the plugin when I have time here and adjust the download in the releases. For now, please use release 0.6.

**Comment by MikkelDK** [comment]
> This is most likely because I've had to setup a new environment for sourcemod for myself. Tried using WSL with some 32bit fixes. I'll recompile the plugin when I have time here and adjust the download in the releases. For now, please use release 0.6.

@PhlexPlexico it was from 0.6 release. so I did "compile" it from windows PC. and works fine after. :D

**Comment by PhlexPlexico** [comment]
Er, apologies. I mean release 0.5 if it's causing you troubles.

**Comment by PhlexPlexico** [comment]
Plugin has been updated on release page.
