### ISSUE TITLE
[BUG] API STATS plugin

### ISSUE THREAD

**Issue by Fortage** [PhlexPlexico/get5-web#170]
**Describe the bug**.
If i download api_stats.smx from 0.6 Release, Plugin get5_apistats.smx failed to load: Unable to load plugin (no debug string table). if i compile plugin,  [get5.smx] Failed to load match config: Steamworks GET request failed, HTTP status code = 0.

**Which Build**
master

I read the last 2 topics about Get5.smx and the api_stats plugin. I tried to install the plugin from 0.5 Release, it gives an error [get5.smx] Failed to load match config: Steamworks GET request failed, HTTP status code = 0. Help = (

**Comment by PhlexPlexico** [comment]
Hi! 

I'm not sure about the 0.6 release. @MikkelDK may have the plugin, if he could provide that I'll adjust the release. I no longer have my SM environment for compiling, so it's kind of difficult for me to compile it right now.

As for the GET request failing, that is an issue with not being able to resolve the host. Get5 repository has a lot more info about it, make sure you're using an actual host for it. Not much I can do to fix that problem as it isn't a plugin problem, but more of a networking issue. Sorry.

**Comment by PhlexPlexico** [comment]
And I believe it's because I compiled with a different version of sourcemod, which isn't supported probably/not backwards compatible. I'll look into it here again.

**Comment by PhlexPlexico** [comment]
Release has been updated with a different SMX, please give that a try.

**Comment by Fortage** [comment]
The problem is solved, I apologize. The fact is that my sys-admin did something, that the OS stopped skating to Steam servers, because of this such problems.
