### ISSUE TITLE
[Feature Request] Season Management & Restriction

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#172]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be better if only the corresponding season is displayed to the user at the time of creating match. Super admins can have the access to create match from any available season.

**Describe alternatives you've considered**
Super admin to assign or lock seasons for users.

**Additional context**
It will be easier for the admin to select the only available season instead of selecting from the drop down list.

**Comment by PhlexPlexico** [comment]
I don't exactly see what you mean by corresponding season? You can have multiple seasons running at once, and the owner/admin can change the dates in which they occur.

**Comment by PhlexPlexico** [comment]
Unless you mean during the match creation that you can only see the seasons you've created, or super-admins can see all seasons? If so, that's a simple query change within [here](https://github.com/PhlexPlexico/get5-web/blob/development/get5/match.py#L178) and you can simply add in an admin check to see if `g.user` is an admin/super admin.

**Comment by xe1os** [comment]
> I don't exactly see what you mean by corresponding season? You can have multiple seasons running at once, and the owner/admin can change the dates in which they occur.

I meant during match creation admin should only see the season that was created by him.

**Comment by xe1os** [comment]
> Unless you mean during the match creation that you can only see the seasons you've created, or super-admins can see all seasons? If so, that's a simple query change within [here](https://github.com/PhlexPlexico/get5-web/blob/development/get5/match.py#L178) and you can simply add in an admin check to see if `g.user` is an admin/super admin and create a different query.

It would be great if we have an option where super admin assigns the seasons to admins. By doing this we can restrict admin to select only a assigned season at the time of match creation.

**Comment by xe1os** [comment]
This is to avoid admins making mistakes selecting wrong season at the time of match creation and realising it later. This ends up screwing the stats.

**Comment by PhlexPlexico** [comment]
I kinda see what you're getting at here. Allow a superadmin to change ownerships of a season to a user, or admin, and the admin has the same power as a user. The way it's currently implemented is that after assignment the user will still be able to edit the dates though, is that alright?

**Comment by xe1os** [comment]
> I kinda see what you're getting at here. Allow a superadmin to change ownerships of a season to a user, or admin, and the admin has the same power as a user. The way it's currently implemented is that after assignment the user will still be able to edit the dates though, is that alright?

Yes. exactly :)

**Comment by PhlexPlexico** [comment]
I believe there is no reason an admin shouldn't be able to select those seasons, it would make sense since they have elevated privileges over any other user, and should still be able to select.

**Comment by xe1os** [comment]
> I believe there is no reason an admin shouldn't be able to select those seasons, it would make sense since they have elevated privileges over any other user, and should still be able to select.

Agreed. but in this case even a user is able to select the other season at the time of match creation page.

**Comment by PhlexPlexico** [comment]
A user is no longer allowed to see seasons that are not owned by them. I can confirm on my with two accounts.
