### ISSUE TITLE
[Feature Request] Points in Team Leaderboard

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/get5-web#173]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Points column to be added in the team leaderboard. Sorting of leaderboard based on points.

**Describe alternatives you've considered**
None.

**Additional context**
Below points to be considered.
Win = 3
Tie = 1
Loss = 0

**Comment by PhlexPlexico** [comment]
I figured it's easier to track total round wins vs lost when it comes down to points. Ideally, there should be no ties in league matches as overtime exists for this very reason.
