### ISSUE TITLE
[Feature Request] Assign SteamID (to create match) from whitelist team.

### ISSUE THREAD

**Issue by MikkelDK** [PhlexPlexico/get5-web#180]
**Is your feature request related to a problem? Please describe.**
It could be nice, if possible...so if I have a team(I did create) but want to whitelist some SteamIDs, so they can use the "team" for creating a match.

**Describe the solution you'd like**
Mikkel own TeamA
Mikkel wants to whitelist PlayerA & PlayerB to could create a match from "TeamA", without then need to create a server/team.

PlayerA > assigned to TeamA
PlayerB > assigned to TeamA
Both have now possible to "login on steam via get5" and without creating the server, without need to create a team on their own SteamID. and just could "create a match" on the same team, as whitelisted.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MikkelDK** [comment]
@PhlexPlexico - dunno about this was/or has been requested =D - about it's possible e.g =D - now where.. it's no longer updated. =D

**Comment by PhlexPlexico** [comment]
I'm not exactly sure what you're asking... Are you wanting to create a match with a "template" team in a sense, and automatically add players to it, so they can login to the server and play? What you should do, is have two teams with no IDs, and just disable "Enforce teams" on the web panel, and have the users sort out teams.

There is a function that you're describing that currently works with the [Discord bot](https://github.com/PhlexPlexico/G5-Bot/tree/feature-5-steam-integration), and there's an experimental branch that will take the SteamID from the users discord info to assign them to a team, and enable check_auths on the server, if that's what you're looking for. I won't be doing that in the webpanel though, as it is unnecessarily complex and it can be avoided by just disabling "Enforce Teams".

If that's not what you're asking, I may need some more clarification. Thanks!

**Comment by MikkelDK** [comment]
@PhlexPlexico Let me try to explain as well I can (incl screenshot)

**Screenshot 1:**
Here, I'm a member of the VNIX team. but I would like to make it possible, so not only (husqiy * owner) can create match from the team, but more, so I can do that (mrc4tt) + the other players, if someone of us is "blocked" for login, because of (failures login)

![screen](http://vps.lindhost.eu/get5/chrome_9fYfZlewKd.png)

**Screenshot 2:**
Here, where I can't find the "VNIX" Team as "create match" since I don't want/without to create a team of it. since it exists. (about it's possible to make, so whitelisted _STEAMID_ has access to exists (**TEAM**) for could create a match!

![screen2](http://vps.lindhost.eu/get5/chrome_3DnumWLSWb.png)

**Screenshot 3: A Chat between me and the owner of VNIX**
He did ask, about it was possible to give (team-member access) (I did try, from the prod_config.py which don't help) - But it wasn't possible. but which be a nice feature if it was possible. - without team-member&me need to create server&team again, when it exists e.g (as optional)
![screen3](http://vps.lindhost.eu/get5/steamwebhelper_c7QdxIZ4wC.png)

**Comment by PhlexPlexico** [comment]
You can't give mutli users access to a team, only one person can own a team. There is an option in the config to allow admins/super_admins to create "Public teams" where anyone can use the team to create matches. 

An admin has to create a team (or get a super_admin to edit the team, and enable "Public Team") and then anyone who can login to the team panel can create matches with the public team.

**Comment by PhlexPlexico** [comment]
Any update for this?
