### ISSUE TITLE
[BUG] URL broken after Backup restored 

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-web#184]
**Describe the bug**
After any backup is loaded via Panel , the URL is broken again redirecting itself from `website.com/match/1 to website.com/match/1/match/1`

**Which Build**
development

**To Reproduce**
1. Try to restore any backups
2. See the error on the webpage

**Expected behavior**
Normal Web panel to that URL.

**Comment by PhlexPlexico** [comment]
Latest development commit should fix it.
