### ISSUE TITLE
[Off-Topic] EOL

### ISSUE THREAD

**Issue by dMwJr** [PhlexPlexico/get5-web#191]
Could you expand on: Some new development is coming down the pipe elsewhere, which I hope will help other developers make their own implementations of get5-web.

Where do we look towards for future development?

**Comment by mrc4tt** [comment]
No update coming.

I don't think, there will be changes. Since we don't dev on it anymore!

**Comment by PhlexPlexico** [comment]
There's a few places if you would like something more up to date. I know FlowingSPDG has a new project that is working on directly importing get5-web into GoLang. It's still a WIP but it should be enough to startup some matches and what-not, it can be found [here](https://github.com/FlowingSPDG/get5-web-go). I know there still are some features that are missing, such as demo uploading and vetoes being displayed.

As for things I'm working on, I'm slowly chipping away at completing an Express API [here](https://github.com/PhlexPlexico/G5API) for whenever I have the time/ability to work on it. I haven't had much time to go heads-down back into it, and it's more of a comprehensive middleware/back-end so people can create their own front-ends using tools like Vue, ReactJS, or even Angular. Most of that should be complete, but tests still need to be implemented to ensure that results are successful, as well as some improvements to the authentication structure. But, this API will hopefully allow other people to easily setup a database, and get going on creating their own fancy front-ends, without the issue of dealing with any database, or middleware setup.

And lastly, as per this project. Development is done. I haven't archived yet as I know there will still be some questions coming in about setup. Even though Python2.7 is End-Of-Life'd, I know people will still be setting up this web panel, even though there are better alternatives being worked on. I don't plan on doing anymore development on this as I lost my environment, no longer use Python2.7, finished the league I was using with this manager, and wanted to learn a new language. 

Hope this helps and answers your questions on where to look!
