### ISSUE TITLE
[BUG] [get5_apistats.smx] There was a problem: Failed FTP upload: 553

### ISSUE THREAD

**Issue by xxTeDYxx** [PhlexPlexico/get5-web#193]
I have good params in get5_api and i have:

L 04/04/2020 - 20:55:33: Info (map "de_mirage") (file "/home/XXXXXX/csgo/addons/sourcemod/logs/errors_20200404.log")
L 04/04/2020 - 20:55:33: [get5_apistats.smx] There was a problem: Failed FTP upload: 553

**Comment by PhlexPlexico** [comment]
https://bobcares.com/blog/ftp-error-553/
