### ISSUE TITLE
Individual Stats

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/get5-web#37]
A user should be able to see their individual stats over the course of playing on the site.

**Comment by PhlexPlexico** [comment]
This may have to add the Steam ID from players to a match. Names are not unique enough.

**Comment by MikkelDK** [comment]
> This may have to add the Steam ID from players to a match. Names are not unique enough.

I agree. Steam ID (SteamID64 e.g, without its name!)

**Comment by PhlexPlexico** [comment]
Just realized that PlayerStats class has a SteamID associated with it. This makes things a lot easier as we can just iterate through the instances on a steamID lookup (for example... `/stats/<int:steamID>`) and grab all the PlayerStats with that steam ID and average it out.

**Comment by PhlexPlexico** [comment]
From the good ol' use of sums and averages, we can query all the data at once and get sums and avergaes of everything
