### ISSUE TITLE
Player Name Assignment on Teams

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/get5-web#47]
Instead of relying on people's names in Steam, we can abuse the get5 player name setting on match load to give players specific names. Will include modifying the following:

Teams
Build_match_dict
Get5_tests
Database

This shouldn't take too long to complete. Maybe start after I get used to the testing framework.

**Comment by MikkelDK** [comment]
Dunno, about you, is planned to-do like (as an example this):

1) Creating a team on get5-web
2) Typo SteamID64 + custom nickname?
3) Creating a match.
4) Starting the match + force players(ingame-name to the custom nickname)

As example:
MrC4t*SteelSeries >> custom nickname: mrc4t

(I'm sorry if I posted in the wrong issue, but I was *think* about it here! 👍)

**Comment by PhlexPlexico** [comment]
Essentially that. The team creation page will have 
`Player One: {TextField For SteamID} {Text Field for Custom Nickname}`

It should load in, since we're calling the `SetPlayerName` from the APIStats call... I believe.

**Comment by MikkelDK** [comment]
> Essentially that. The team creation page will have
> `Player One: {TextField For SteamID} {Text Field for Custom Nickname}`
> 
> It should load in since we're calling the `SetPlayerName` from the APIStats call... I believe.

Yeah, correct. which I was thinking, about it did.

**Comment by PhlexPlexico** [comment]
API now sends the usernames if they exist to the API.

**Comment by PhlexPlexico** [comment]
Closing since completed.
