### ISSUE TITLE
FTP Demo Uploads

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/get5-web#53]
Maybe save to a directory and have a connection that pings `x` amount of times per day on game server. If there's files existing, transfer them to the web server that has a publically accessible folder. Could just be an external Cron task on the web server even that calls an ssh session to copy everything then delete it from server, followed by deletion after `y` amount of days.

**Comment by PhlexPlexico** [comment]
Few things that should be done?

- [ ] Add in the SSH configs to the database, encrypt SSH passwords, or better yet use a key and turn off user based auth on servers.
- [ ] When game is complete. check for demo file that's based on the plugin format, may have to bring it into the web panel as well.
- [ ] SSH to a point in the server that will have to be adjusted in Apache where a user can successfully access the demos, most likely in `static`
- [ ] Post Demos to match page
- [ ] Check for demos that are older than two weeks and delete from server.

**Comment by PhlexPlexico** [comment]
Two steps forward one step back. Found an error with Flask WTF 0.14 that isn't storing the boolean values in the server, which means I can't update anything in the forms.

**Comment by PhlexPlexico** [comment]
There's an issue that was posted in the Flask forms github. Could be worth creating a sub class since it may be calling it twice, like the OP in that issue mentioned.

**Comment by PhlexPlexico** [comment]
This could also be to do with 2.2.1 having some issues, where 2.1 was working just fine. Maybe downgrading the version may be within best interest.

**Comment by PhlexPlexico** [comment]
By the looks of it, it does seem to be with the most recent 2.2.1 Forms. Which I don't believe I need, since upgrading was unrelated to the team logos. Will have to downgrade and continue testing! If this is okay, we can start on the encryption again!

**Comment by PhlexPlexico** [comment]
PyCrypto will now be installed in requirements, and the application now requires a `DATABASE_KEY` that is a 16 character string, that will deal with database encryption and decryption.

**Comment by PhlexPlexico** [comment]
"subprocess.Popen(["scp", filename, "%(user)s@%(server)s:%(remotepath)s" % vars]).wait() is a much better approach than os.system(), which doesn't handle filenames with spaces correctly" leaving for thought.

**Comment by PhlexPlexico** [comment]
On top of this, we will need to make another API call, instead of match finish because GoTV demos can be delayed. Will need to use `void Get5_OnDemoFinished(const char[] filename)` and upload to our server then...

**Comment by PhlexPlexico** [comment]
One issue I am definitely going to run into is getting the absolute path... There's no determined way to tell where the server exactly is, unless you can send the `pwd` via SourceMod.

**Comment by PhlexPlexico** [comment]
Going to need tons of testing, but as of the latest push in development, the plugin should be able to handle demo uploads to an FTP server. It is up to the user to configure it on their web instance as well, or creating a symlink from an FTP directory on their server, to `static/demos` in the web server directory.

**Comment by PhlexPlexico** [comment]
So there is an issue with libcurl and System2, as it seems to get the file size wrong, but we can do a simple check to see if the total uploaded > expected size, because then we are certain it was still uploaded and proceed to process on the game server demo (delete).

Still thinking if it's worth it to zip the demos.

**Comment by PhlexPlexico** [comment]
Now we have a choice to zip demos or not. Sent off a test plugin to @MikkelDK so once we get some initial testing done with an FTP server, we can close this issue off and consider it complete.

**Comment by MikkelDK** [comment]
Seems 7-zip need to be installed, before it will **do make .zip**

I will test again about a few hours. ;-)

**Comment by PhlexPlexico** [comment]
`chmod -R +x /home/nyberg-57/server/csgo/csgo/addons/sourcemod/data/system2`

May have to play with permissions a little bit, in order to allow the 7z to actually run?

**Comment by MikkelDK** [comment]
> `chmod -R +x /home/nyberg-57/server/csgo/csgo/addons/sourcemod/data/system2`
> 
> May have to play with permissions a little bit, in order to allow the 7z to actually run?

I can try! ;)

**Comment by PhlexPlexico** [comment]
Not sure if I'm personally going to use this, as FTP seems to just hate me, but I think there should be enough catch-all errors in order to upload a demo. Tested before using compression and it did seem to work, as tested by @MikkelDK (thanks!).

Going to close for now, if there's any new issues with it, please someone create a ticket and I'll look into it again.
