### ISSUE TITLE
Allow Users to Upload SVGs to images

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/get5-web#64]
If it's an SVG, we should allow the user to load the logo in, much like the PNG, as panorama now uses SVGs to load in a majority of the game. If someone would want to eventually pick this up, that would be great.

**Comment by MikkelDK** [comment]
+ `get5/static/resource/csgo/materials/panorama/images/tournaments/teams/` for SVG. ^^
incl possible to upload PNGs to images (too) maybe direct from web.

**Comment by PhlexPlexico** [comment]
The apistats plugin will also have to be updated to scan for SVGs, and include both logo directories to download for the match.

**Comment by PhlexPlexico** [comment]
Will have to also include updating the API stats plugin, to look for both directories in the application, if the SVG exists then we need to copy it over.

**Comment by TandelK** [comment]
@MikkelDK Does the logos uploaded in panaroma folder work with Scoreboard ?

**Comment by MikkelDK** [comment]
> @MikkelDK Does the logos uploaded in panorama folder work with Scoreboard?

I don't have tested since I'm waiting for apistats will be updated, so it can accept SVG via "get5/static/resource/csgo/materials/panorama/images/tournaments/teams/" as an example.

**Comment by TandelK** [comment]
Can you take a simple logo convert it to svg and put the logo in the above directory and than try to use it ? I dont have any CSGO servers as of now.

**Comment by PhlexPlexico** [comment]
While this is still fresh, I should be going through this. The plugin requires both `LOGO_DIR` and `LOGO_NEW_DIR` if we send in an SVG. The upload form will now require an `SVG` option, and that should make most of it work. If PNG doesn't exist, fallback onto loading the `SVG` on the panel, or display none if they don't exist.

**Comment by PhlexPlexico** [comment]
https://pypi.org/project/svglib/ also needed to save SVG as PIL does not support SVG files.

**Comment by PhlexPlexico** [comment]
Seems to be working for the few images that I've uploaded. Closing now.
