### ISSUE TITLE
Create Autoinstall Script for Ubuntu /CentOS system. 

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-web#68]
Create a auto install script for the  downloading panel and modifying the config directly with install script. Something similar script like LinuxLSGM

**Comment by PhlexPlexico** [comment]
I won't be taking care of this as it isn't _directly_ related to the webpanel. If you'd like to make one then by all means go for it, but I did move the install instructions over to the wiki, and will be updating as things change. Maybe once I'm done with the project I'll look into it.

**Comment by PhlexPlexico** [comment]
See https://github.com/TandelK/Get5-AutoInstallScript

Closing for now.
