### ISSUE TITLE
[Feature Request] Define Spectators for Matches

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-web#71]
Allow the admins via panel to add in Game Admins SteamID and Casters Steam ID in a page for Admins and Caster. After that allow them to be selected for Match Creation area. If the IDs are selected they should be automatically added to Spectator Teams for Admins as well as Caster. Also for caster send a command to define them 

`tv_allow_camera_man_steamid STEAMID64`

**Comment by TandelK** [comment]
Some extra function , just use database users section but define extra variable for them, currently for whitelisted ids it is 0 , for Webpanel admins they are 1 and for In Game Admins should be set to 2 and for Casters set to 3 

Also make sure to show main WebPanel Admins for Admins area as they might be also in  the main admin of the CSGO Server.

**Comment by PhlexPlexico** [comment]
I definitely wouldn't want the spectators/observers to be set for defined people each time a match is created. There's plenty of times where someone is doing it as a one-off, and I would much prefer they are given access on a case-by-case basis for the server. 

With that being said, moving the admins to the database and whitelisted people may not be that bad of an idea. Will have to revisit later.

**Comment by PhlexPlexico** [comment]
Since I'm probably going back soon to work on the match pages (enabling/disabling knife), I think I can probably add this in as well, since I have run into this issue of adding spectators to the match.

**Comment by TandelK** [comment]
The reason why i asked for this feature because we dont have to individually after each created match we have to again add Admins in Spectators or Casters via Panel , instead this will bring more easy way and also tournament admins will be easy to setup so they also have defined matches they have to watch. If there is issue we still have add a player to spectator section available.

**Comment by PhlexPlexico** [comment]
I would say this would be more for adding spectators to the matches, since they should be able to see everything, and the spectator team is allowed to do so. Updated title to reflect change, and will look into adding it into the match table, since it should be standard across all maps in a series.

**Comment by PhlexPlexico** [comment]
Latest commit on development should now add this feature. I did some very basic testing, would you mind confirming it works as intended?
