### ISSUE TITLE
[BUG] Match Continues When Both Teams Forfeit

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/get5-web#72]
If both teams don't show it, the web panel doesn't seem to handle it properly, as the match still says pending when both teams forfeit. Need to examine why it fails to set the winner to none, Reported originally by @TandelK in the original repo. Need to adjust the logic on forfeit.

**Comment by TandelK** [comment]
The status is still pending because the Database status of Match Start Time is set to NULL by default and still stays same even if the match is completed. As the timer gets over of the cvar and the End Time is registered in Database leading to complete status.

**Comment by PhlexPlexico** [comment]
Oh I get it, when the forfeit is called, the API call `/start` is never called. So easy fix, just under the forfeit, set the MatchTime start here after we determine its a forfeit:
https://github.com/PhlexPlexico/get5-web/blob/master/get5/api.py#L57

Thanks! Makes more sense then me sifting through everything.

**Comment by PhlexPlexico** [comment]
Adjusted the finish api call on if there is a forfeit, and the start time is set to none, we set it to the current time.

**Comment by TandelK** [comment]
@PhlexPlexico this has only solved one condition if both the teams does not follow up that cvar and match is forfeited for not showing up what should we do with API ?

**Comment by PhlexPlexico** [comment]
If both teams don't show, a reply from the API does not send in a winnerString, or it is set to None. (I believe)[https://github.com/PhlexPlexico/get5-web/blob/master/sourcemod_plugin/get5_apistats/scripting/get5_apistats.sp#L374] that would be the case. So I added an else case that sets the winner to none (both teams score 0), and start time is set to utcnow. Should that not work?

**Comment by TandelK** [comment]
Yeah that should work if should be working fine than. The issue as i told before automatically making team 2 winner as team 1 condition was getting checked first i and than team 2 so this should overwrite the condition and make the panel work correct. I will check the new update later in 3-4 hours when i am free.

**Comment by PhlexPlexico** [comment]
Whatever get5 sends isn't really up to me. If both teams don't show, I believe it should set winner = none, and the API plugin will pick it up and send, and then the webpanel will now set the start time and end time, and set series results to 0,0.

**Comment by PhlexPlexico** [comment]
Does this still have the same result? I'm not sure if I made any adjustments in commits, but I vaguely remember changing some logic to ensure a FFW/FFL was handed out.

**Comment by PhlexPlexico** [comment]
Closing as there has been no update in a few months. Either reopen this ticket or create a new one if you run into this issue again. I do believe it's a get5 issue and what events it sends when both teams forfeit, as I don't think it's anything I can immediately "fix" (or has been fixed already). Thank you!
