### ISSUE TITLE
[Feature Request] Safe Delete Cancelled Matches

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/get5-web#73]
Have a button that deletes a users' cancelled matches, only if they haven't been played. Or if they have, delete all map/player/match stats associated with it for a safe delete.

**Comment by PhlexPlexico** [comment]
I think for this we should have the user for sure be an admin, especially since some matches can still have player_stats associated with it.

**Comment by TandelK** [comment]
We can use a special id of admin id which will be like super admin ?

**Comment by PhlexPlexico** [comment]
No, it will be the regular admins for now that are defined in the config file, as it's an admins job. Could even make it optional to have it for every user and just delete the cancelled matches that are under a user ID.
