### ISSUE TITLE
[Feature Request] Change Layout Site Title Based on Config Value

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-web#74]
I know its simple for web developers and upload the Logos manually but making more easy way to integrate in settings config.  Lot of people dont wanna modify layout.html as it has updates and git pull requires to be remove custom changes so it will be better to move onto config settings. If anyone doesnt define logo name you can define Panel Name .

**Comment by MikkelDK** [comment]
I agree!

**Comment by PhlexPlexico** [comment]
Oh, it's not the panel logo you're asking, it's the title of the page on the layout. I was going to say the logo you just replace the png file that's in the repo with what you want, and if you're doing the setup for the site anyways, you should have the knowledge to drag and drop a new logo. As for the title of the webpage, that I can do.

**Comment by PhlexPlexico** [comment]
Now in latest dev build, `WEBPANEL_NAME` will change the title of the webpanel on the browser.

**Comment by PhlexPlexico** [comment]
Please comment if this is what you needed, and close if it's successful!
