### ISSUE TITLE
[Bug] Edit/Delete Team

### ISSUE THREAD

**Issue by MikkelDK** [PhlexPlexico/get5-web#75]
Error for Delete team:
> Sorry, unexpected error: (_mysql_exceptions.IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`get5`.`match`, CONSTRAINT `match_ibfk_3` FOREIGN KEY (`team2_id`) REFERENCES `team` (`id`))') [SQL: DELETE FROM team WHERE team.id = %s] [parameters: (2,)] (Background on this error at: http://sqlalche.me/e/gkpj)

Error for Edit/Add Team:
`Sorry, unexpected error: 'unicode' object has no attribute 'filename'`

**Do I need to delete the database, and install from new?**

**Comment by TandelK** [comment]
@MikkelDK Did you do a db upgrade command ?  As most of the times after development updates please always do db upgrade as well requirements update and than do apache restart

**Comment by MikkelDK** [comment]
> @MikkelDK Did you do a db upgrade command ? As most of the times after development updates please always do db upgrade as well requirements update and than do apache restart

@TandelK Yup, I did! ;) still same! :-)

**Comment by PhlexPlexico** [comment]
#73

It's because he started a match with a team and it recorded stats. So therefore there's foreign key constraints on the database.

**Comment by PhlexPlexico** [comment]
Closing this as it has already been reported and is under thought on how to fix/if we need to fix.
