### ISSUE TITLE
[Feature Request] Add Leaderboard for Individual Players

### ISSUE THREAD

**Issue by TandelK** [PhlexPlexico/get5-web#91]
The same way leaderboard for teams is added we can get Leaderboard for Individual players also ? We can compare it mainly on Kills / Death and also we should be able to use Sorting in website why which category the player is leading 

1) K/D Ratio
2) Ratings
and many more. 

There should be seperate leaderboard for Specific Season as well as Global Leaderboard for all the seasons.

**Comment by PhlexPlexico** [comment]
Probably would just be a combination of `stats/<steamid>` and just throwing it in a leaderboard style. Will need to think of what to use for a route link... Maybe `/leaderboard/player/<optional season id>`?

**Comment by TandelK** [comment]
we can have it in 2 simple way /leaderboard/global or leaderboard/seasonid

**Comment by PhlexPlexico** [comment]
Both those already exist. /leaderboard shows the team standings of all time, /leaderboard/season/<seasonID> shows the team standings for a season.

**Comment by TandelK** [comment]
ok than we can use /stats/global or /stats/seasonid

**Comment by PhlexPlexico** [comment]
Now in development build, data can be seen via /leaderboard/players and is using datatables. PRs are welcome to fix up some of the now broken CSS for that!

**Comment by PhlexPlexico** [comment]
Removed Datatables CSS which just gets rid of some icons, not really needed. Closing as the leaderboard is complete.
